service: sample-api
useDotenv: true
frameworkVersion: '3'

provider:
  name: aws
  region: 'us-east-1'
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'sns:*'
          Resource: 'arn:aws:sns:us-east-1:${env:AWS_ACCOUNT}:*'
  runtime: nodejs20.x
  environment:
    AWS_ACCOUNT: ${env:AWS_ACCOUNT}
    SLACK_URL: ${env:SLACK_URL}

functions:
  notification-slack:
    handler: src/notificationSlack.handler
    events:
      - sns:
          arn: arn:aws:sns:us-east-1:${env:AWS_ACCOUNT}:SLACK_NOTIFICATION
